# -*- coding: utf-8 -*-
"""openenv_2048_grpo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EOHvaN8WvLt9d5DfhjhCwlbh9nCjJVDh
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -Uq git+https://huggingface.co/spaces/Jakemu/openspiel_env

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -Uq trl[vllm] git+https://huggingface.co/spaces/Jakemu/openspiel_env

!pip install -Uq transformers torchao==0.16.0 kernels liger-kernel bitsandbytes

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -q --no-build-isolation flash-linear-attention

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# # install causal_conv1d==1.6.0
# %%capture
# !pip install /content/drive/MyDrive/wheel/causal_conv1d-1.6.0-cp312-cp312-linux_x86_64.whl

# mv /root/.cache/pip/wheels/9a/1e/2e/a0c04cf5c155486922378c8a2f111ac9705a354a949dd724a4 /content/drive/MyDrive/wheel/

"""### Log in to Hugging Face

Log in to your **Hugging Face** account to save your fine-tuned model, track your experiment results directly on the Hub or access gated models. You can find your **access token** on your [account settings page](https://huggingface.co/settings/tokens).
"""

from huggingface_hub import notebook_login
notebook_login()

import os
import wandb
from google.colab import userdata
wandb_api_key = userdata.get('WANDB_API_KEY')
os.environ["WANDB_PROJECT"] = "openenv-2048"
wandb.login(key=wandb_api_key)

from openspiel_env import OpenSpielEnv, OpenSpielAction, OpenSpielObservation

class Env2048:
  def __init__(self):
      self.client = OpenSpielEnv(base_url="https://jakemu-openspiel-env.hf.space").sync()

  def reset(self, **kwargs) -> None | str:
      result = self.client.reset()

      self.legal_actions = result.observation.legal_actions
      self.reward = 0.0
      self.done = False

      return result.observation

  def move(self, action_id: str) -> str:
      """
      Execute a move in the 2048 game.

      Args:
          action_id: The direction to move. 0 for Up, 1 for Right, 2 for Down, 3 for Left.

      Returns:
          str: A string representation of the observation state after the move.
      """
      result = self.client.step(OpenSpielAction(action_id=action_id, game_name="2048"))
      self.result = result
      self.legal_actions = result.observation.legal_actions
      self.reward = result.reward
      self.done = result.done

      return result.observation

env2048 = Env2048()

result = env2048.reset()

result

current_state = result.info_state
current_state

import numpy as np
def convert_to_board(current_state):
    n = len(current_state)
    size = int(np.sqrt(n))
    board = np.array_split(np.array(current_state, dtype = int), size)
    board = [x.tolist() for x in board]
    return board, size
# convert_to_board(current_state)

#@title (Collapsible) 2048 Game Renderer
def render_board(obs, colors: bool = False, border: bool = True, dot_for_zero: bool = True):
    """
    Pretty-print the board using Pandas for clean Colab output.
    """
    import pandas as pd
    from IPython.display import display

    b, size = convert_to_board(obs)

    # Display as a nicely formatted HTML table using Pandas
    df = pd.DataFrame(b).replace(0, '')

    # Style the dataframe to look like a game board
    styled_df = (df.style
                 .set_properties(**{
                     'text-align': 'center',
                     'font-size': '18pt',
                     'font-weight': 'bold',
                     'width': '25px',
                     'height': '25px',
                     'border': '2px solid #bbada0',
                     'background-color': '#cdc1b4',
                     'color': '#776e65'
                 })
                 .hide(axis='index')
                 .hide(axis='columns'))
    display(styled_df)

render_board(current_state)

current_state = env2048.move(0).info_state
render_board(current_state)

current_state = env2048.move(1).info_state
render_board(current_state)

current_state = env2048.move(2).info_state
render_board(current_state)

current_state = env2048.move(3).info_state
render_board(current_state)

env2048.client.close()

del env2048

env2048 = Env2048()

result = env2048.reset()
result

from typing import Callable
import itertools
import time
import signal
from functools import wraps

def execute_with_time_limit(seconds):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            def handler(signum, frame):
                raise TimeoutError(f"Timed out after {seconds} seconds.")

            # Set the signal handler and alarm
            old_handler = signal.signal(signal.SIGALRM, handler)
            signal.alarm(seconds)
            try:
                result = func(*args, **kwargs)
            finally:
                # Disable the alarm after function finishes
                signal.alarm(0)
                signal.signal(signal.SIGALRM, old_handler)
            return result
        return wrapper
    return decorator

def _execute_strategy(env: Env2048, strategy: Callable, current_state):
    assert callable(strategy)

    steps = 0
    total_reward = 0

    while not current_state.done:

        board, size = convert_to_board(current_state.info_state)
        action = strategy(board)
        try:
            action = int(action)
        except:
            return steps, False

        steps += 1
        if type(action) is not int or action not in current_state.legal_actions:
            return steps, max(itertools.chain.from_iterable(board)) == 2048, current_state.info_state

        current_state = env.move(action_id=action)

        if env.reward is not None:
            total_reward += env.reward

    return steps, max(itertools.chain.from_iterable(board)) == 2048, current_state.info_state

@execute_with_time_limit(5)
def execute_strategy(env: Env2048, strategy : Callable, current_state : OpenSpielObservation):
    return _execute_strategy(env, strategy, current_state)

def always_move_left(board):
    return 3

current_state = env2048.reset()

try:
    steps, if_done, info_state = execute_strategy(env2048, always_move_left, current_state)
except TimeoutError as e:
    print(f"Timed out with error = {str(e)}")

steps, if_done, info_state

env2048.client.close()

"""# Code Execution"""

import ast
import sys

def check_python_modules(code_string):
    try:
        tree = ast.parse(code_string)
    except SyntaxError as e:
        return False, {"error": f"Syntax Error: {e}"}

    stdlib_imports = set()
    non_stdlib_imports = set()
    relative_imports = 0

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                base_module = alias.name.split('.')[0]
                if base_module in sys.stdlib_module_names:
                    stdlib_imports.add(base_module)
                else:
                    non_stdlib_imports.add(base_module)
        elif isinstance(node, ast.ImportFrom):
            if node.level is not None and node.level > 0:
                relative_imports += 1
            if node.module:
                base_module = node.module.split('.')[0]
                if base_module in sys.stdlib_module_names:
                    stdlib_imports.add(base_module)
                else:
                    non_stdlib_imports.add(base_module)

    info = {
        'stdlib': list(stdlib_imports),
        'non_stdlib': list(non_stdlib_imports),
        'relative_imports': relative_imports
    }

    # It is OK if there are no non-standard libraries and no relative imports
    ok = len(non_stdlib_imports) == 0 and relative_imports == 0
    return ok, info

sample = """
def strategy(board):
    import math
    from typing import Callable
    return "0"
"""
ok, info = check_python_modules(sample)
print("Only Python imports?", ok)
print(info)

sample = """
def strategy(board):
    from numpy import matmul
    return "0"
"""
ok, info = check_python_modules(sample)
print("Only Python imports?", ok)
print(info)

def create_locked_down_function(code_string):
    restricted_globals = {"__builtins__": __builtins__}
    local_namespace = {}
    exec(code_string, restricted_globals, local_namespace)

    for name, obj in local_namespace.items():
        if callable(obj):
            return obj
    raise ValueError("No function defined in the provided code.")

function = """
def import_numpy():
    np.matmul
    print("Success")
"""
f = create_locked_down_function(function)
try:
    f()
except Exception as e:
    print(str(e))

function = """
def add(a, b):
    def adder(a):
        return a + b
    return adder(b) + b
"""
f = create_locked_down_function(function)
try:
    print(f(10, 20))
except Exception as e:
    print(str(e))

prompt = """
Create a new short 2048 strategy using only native Python code.
You are given a list of list of numbers for the current board state.
Output one action for "0", "1", "2", "3" on what is the optimal next step.
Output your new short function in backticks using the format below:
```python
def strategy(board):
    return "0" # Example
```
All helper functions should be inside def strategy. Only output the short function `strategy`.
""".strip()
print(prompt)

"""# Reward functions

We now design a `extract_function` function which simply extracts the function wrapped in 3 back ticks.

And 3 reward functions:

1. `function_works` which rewards the model if the strategy is a valid Python function.
2. `no_cheating` which checks if the function imported other modules, and if it did, we penalize it.
3. `strategy_succeeds` which checks if the game strategy actually succeeds in attaining 2048 after running the auto-generated strategy.
"""

def extract_function(text):
    if text.count("```") >= 2:
        first = text.find("```") + 3
        second = text.find("```", first)
        fx = text[first : second].strip()
        fx = fx.removeprefix("python\n")
        fx = fx[fx.find("def"):]
        if fx.startswith("def strategy(board):"): return fx
    return None
print(extract_function(prompt))

ok, info = check_python_modules("def a")
ok, info

def function_works(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        function = extract_function(response)
        if function is not None:
            ok, info = check_python_modules(function)
        if function is None or "error" in info:
            score = -2.0
        else:
            try:
                new_strategy = create_locked_down_function(function)
                score = 1.0
            except:
                score = -0.5
        scores.append(score)
    return scores

def no_cheating(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        function = extract_function(response)
        if function is not None:
            ok, info = check_python_modules(function)
            scores.append(1.0 if ok else -20.0) # Penalize heavily!
        else:
            scores.append(-1.0) # Failed creating function
    return scores

import numpy as np

def strategy_succeeds(completions, **kwargs):
    scores = []
    for completion in completions:
        printed = False
        score = 0
        response = completion[0]["content"]
        function = extract_function(response)
        # print(function)

        if function is not None:
            ok, info = check_python_modules(function)
        if function is None or "error" in info:
            scores.append(0)
            continue
        try:
            new_strategy = create_locked_down_function(function)
        except:
            scores.append(0)
            continue
        try:
            # Reset OpenEnv to an initial state!
            env2048 = Env2048()
            current_state  = env2048.reset()
            steps, if_done, info_state = execute_strategy(env2048, new_strategy, current_state)
            # print(f"Steps = {steps} If Done = {if_done}")
            # print(render_board(info_state))
            if if_done:
                scores.append(20.0) # Success - massively reward!
            else:
                scores.append(2.0) # Failed but function works!
        except TimeoutError as e:
            print(f"Exception = {str(e)}")
            scores.append(-1.0) # Failed with timeout
        except Exception as e:
            print(f"Exception = {str(e)}")
            scores.append(-3.0) # Failed
        finally:
            env2048.client.close()
    return scores

mock_completions = [
    [{"content": "Here is a basic strategy:\n```python\ndef strategy(board):\n    return 0\n```"}],
    [{"content": "Here is a cheating strategy:\n```python\ndef strategy(board):\n    import os\n    return 1\n```"}],
    [{"content": "No function here!"}]
]

print("function_works scores:", function_works(mock_completions))
print("no_cheating scores:", no_cheating(mock_completions))
print("strategy_succeeds:", strategy_succeeds(mock_completions)) # Uncomment to test (may take time due to environment execution)

from datasets import Dataset

dataset = Dataset.from_dict({"prompt": [[{"role": "user", "content": prompt}] for _ in range(3000)]})

model_name = "/content/drive/MyDrive/huggingface/models/Qwen3.5-9B"
output_dir = "Qwen3.5-9B-2048-grpo"

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    attn_implementation="kernels-community/flash-attn2"  # other options: kernels-community/vllm-flash-attn3, kernels-community/paged-attention
)

import torch
from transformers import BitsAndBytesConfig
from trl import GRPOConfig

model_init_kwargs = {
    "quantization_config": BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
    ),
    "attn_implementation": "kernels-community/flash-attn2",
    "dtype": torch.bfloat16,
}

grpo_config = GRPOConfig(
    # Training schedule / optimization
    model_init_kwargs=model_init_kwargs,
    use_liger_kernel=True,
    num_train_epochs=1,
    learning_rate=1e-6,
    gradient_accumulation_steps=16,
    per_device_train_batch_size=1,
    warmup_steps=10,
    optim="adamw_torch",
    max_grad_norm=1.0,

    # GRPO configuration
    num_generations=8,
    max_completion_length=1024,
    log_completions=True,
    num_completions_to_print=2,
    chat_template_kwargs={"enable_thinking": False},

    # vLLM configuration
    use_vllm=True,
    vllm_mode="colocate",
    vllm_gpu_memory_utilization=0.35,
    vllm_max_model_length=3072,

    # Logging / reporting
    output_dir=output_dir,
    report_to="wandb",
    # trackio_space_id=output_dir,
    logging_steps=1,
    save_steps=10,
    save_total_limit=1,

    # Memory optimization
    gradient_checkpointing=True,

    # Hub integration
    push_to_hub=True,
)

import sys
import os
from peft import LoraConfig

# Colab(Jupyter) 환경에서 vLLM fileno() 에러를 우회하기 위한 패치
try:
    sys.stdout.fileno()
except:
    sys.stdout.fileno = lambda: os.open(os.devnull, os.O_WRONLY)

from trl import GRPOTrainer

peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    task_type="CAUSAL_LM",
)

trainer = GRPOTrainer(
    # attn_implementation="kernels-community/flash-attn2",
    model=model_name,
    reward_funcs = [
        function_works,
        no_cheating,
        strategy_succeeds,
    ],
    train_dataset=dataset,
    args=grpo_config,
    peft_config=peft_config,
)

"""Show memory stats before training"""

import torch

gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)

print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

"""And train!"""

trainer_stats = trainer.train()

"""Show memory stats after training"""

used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_training = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
training_memory_percentage = round(used_memory_for_training / max_memory * 100, 3)

print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training.")
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_training} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {training_memory_percentage} %.")

"""## Save and push to Hub"""

# --- 1. LoRA 어댑터만 저장 및 허브에 업로드 (기본 동작, 용량이 작음) ---
trainer.save_model(output_dir)
trainer.push_to_hub(commit_message="Upload LoRA adapter")

# --- 2. 베이스 모델과 어댑터를 병합(Merge)해서 업로드하고 싶다면 아래 주석을 해제하세요 ---
# from peft import AutoPeftModelForCausalLM
# import torch

# # VRAM 확보를 위해 기존 trainer 모델 정리 (선택사항)
# # del trainer
# # torch.cuda.empty_cache()

# # 저장된 어댑터 경로에서 모델을 로드하고 병합
# peft_model = AutoPeftModelForCausalLM.from_pretrained(output_dir, torch_dtype=torch.bfloat16, device_map="auto")
# merged_model = peft_model.merge_and_unload()

# # 병합된 전체 모델을 Hub에 업로드 (원하는 레포지토리 이름 지정)
# merged_repo_name = f"{output_dir}-merged"
# merged_model.push_to_hub(merged_repo_name, commit_message="Upload merged full model")
# tokenizer = AutoTokenizer.from_pretrained(model_name)
# tokenizer.push_to_hub(merged_repo_name)

"""## Load the fine-tuned model and run inference

Now let's test our fine-tuned model by loading it and playing a game of Wordle.
We use the same `WordleEnv` class to interact with the environment, and generate model responses with standard Transformers inference.
"""

from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "sergiopaniego/wordle-grpo-Qwen3-1.7B"  # Replace with your HF username or organization

fine_tuned_model = AutoModelForCausalLM.from_pretrained(model_name, dtype="bfloat16", device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(model_name)

import json


def play_wordle(model, tokenizer):
    env = WordleEnv()
    initial_observation = env.reset()

    print("Initial observation:")
    print(initial_observation)
    print()

    messages = [{"role": "user", "content": prompt}]
    if initial_observation:
        messages.append({"role": "user", "content": initial_observation})

    for turn in range(6):
        if env.done:
            break

        prompt_text = tokenizer.apply_chat_template(
            messages,
            add_generation_prompt=True,
            tokenize=False,
            enable_thinking=False,
        )
        model_inputs = tokenizer([prompt_text], return_tensors="pt").to(model.device)
        generated_ids = model.generate(**model_inputs, max_new_tokens=512)
        output_ids = generated_ids[0][len(model_inputs.input_ids[0]):]
        generated_text = tokenizer.decode(output_ids, skip_special_tokens=True)

        print(f"Turn {turn + 1} - Model output: {generated_text}")

        # Try to parse tool call from the generated text
        try:
            # Try to extract a guess from tool call format or bracket format
            if "guess" in generated_text:
                # Parse JSON tool call
                start = generated_text.index("{")
                end = generated_text.rindex("}") + 1
                args = json.loads(generated_text[start:end])
                if "arguments" in args:
                    args = args["arguments"]
                guess_word = args.get("guess", "")
            else:
                # Fallback: extract from brackets [word]
                import re
                match = re.search(r"\[([a-zA-Z]{5})\]", generated_text)
                guess_word = match.group(1) if match else generated_text.strip()[:5]

            feedback = env.guess(f"[{guess_word}]")
            print(f"         Guess: {guess_word} | Reward: {env.reward}")
            print(f"         Feedback: {feedback.strip()}")
            print()

            messages.append({"role": "assistant", "content": generated_text})
            messages.append({"role": "user", "content": feedback})
        except Exception as e:
            print(f"         Error: {e}")
            break

    print(f"Game finished! Final reward: {env.reward}")
    print(f"Done: {env.done}")

"""Let's play the game!"""

play_wordle(fine_tuned_model, tokenizer)

"""## vLLM Inference with Sampling Parameters

Below is an example of how to perform fast inference using **vLLM** instead of standard Hugging Face Transformers. We use `SamplingParams` to control the generation process (temperature, top_p, etc.).

*Note: vLLM typically requires merged model weights. If you want to use the LoRA adapter directly, you need to initialize the engine with `enable_lora=True` and pass a `LoRARequest`.*
"""

from vllm import LLM, SamplingParams

# 1. Define Sampling Parameters
sampling_params = SamplingParams(
    temperature=0.7,
    top_p=0.95,
    max_tokens=512,
    repetition_penalty=1.05
)

# 2. Initialize the vLLM engine
# For testing, we use the base model. If you merged your model earlier,
# replace `model_name` with your `merged_repo_name` or merged local path.
print(f"Loading model: {model_name} into vLLM...")
llm = LLM(
    model=model_name,
    gpu_memory_utilization=0.5, # Adjust based on available VRAM
    max_model_len=3072,
    tensor_parallel_size=1
)

# 3. Format the prompt with the chat template
print("Formatting prompt...")
tokenizer = llm.get_tokenizer()
messages = [{"role": "user", "content": prompt}]
formatted_prompt = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

# 4. Run Inference
print("Generating response...")
outputs = llm.generate([formatted_prompt], sampling_params)

# 5. Display the output
for output in outputs:
    generated_text = output.outputs[0].text
    print("\n--- Generated Strategy ---")
    print(generated_text)

